INSERT INTO BOOK (ID, NAME, DESCRIPTION, AUTHOR) VALUES (1, 'HARRY POTTER', 'PIEDRA FILOSOFAL', 'JK. ROWLING');
INSERT INTO BOOK (ID, NAME, DESCRIPTION, AUTHOR) VALUES (2, 'HARRY POTTER', 'CAMARA DE LOS SECRETOS', 'JK. ROWLING');
INSERT INTO BOOK (ID, NAME, DESCRIPTION, AUTHOR) VALUES (3, 'HARRY POTTER', 'PRISIONERO DE ASKABAN', 'JK. ROWLING');
INSERT INTO BOOK (ID, NAME, DESCRIPTION, AUTHOR) VALUES (4, 'HARRY POTTER', 'CALIZ DE FUEGO', 'JK. ROWLING');
INSERT INTO BOOK (ID, NAME, DESCRIPTION, AUTHOR) VALUES (5, 'HARRY POTTER', 'ORDEN DEL FENIX', 'JK. ROWLING');
INSERT INTO BOOK (ID, NAME, DESCRIPTION, AUTHOR) VALUES (6, 'HARRY POTTER', 'PRINCIPE MESTIZO', 'JK. ROWLING');
INSERT INTO BOOK (ID, NAME, DESCRIPTION, AUTHOR) VALUES (7, 'HARRY POTTER', 'RELIQUIAS DE LA MUERTE', 'JK. ROWLING');